---
title: "A Provocation: Visualizing Modeled Social Networks"
author: "jimi adams, University of South Carolina"
date: "`r format(Sys.Date(), '%Y %B %d')`"
output:
  pdf_document: default
  html_document: default
bibliography: modviz.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Abstract**: Network scholarship regularly leverages visualizations. 
They are thought to enhance readers' recall, interpretation, and simplification of scholar's intended takeaways. 
However, by representing the specifics of single empirical cases, these visualization strategies may not optimize how well they accomplish our scientific purposes. 
In particular, they may: 
(1) be overly complex in ways that obfuscate what we can learn from them, (2) draw attention to the particularities of the case, rather than the general principles the case is examined to characterize, 
(3) be difficult to precisely replicate, raising questions about consistency in interpretation, and 
(4) introduce potential risks that could violate research ethical standards. 
To address these, this paper provokes the field to consider whether presenting *modeled* network results--in lieu of empirical cases--retains the aims of network visualization, while potentially overcoming some of the limitations of existing practice.

\textcolor{red}{NOTE: This is very much a fledgling idea that isn't yet ready for citation/sharing. If you're interested in helping me bring this to life, please reach out. Otherwise, for now, think of it as a musing... Also, I'd initially envisioned submitting as a Viz paper to \textit{Socius}, and have since submitted it to \textit{Social Networks} for their theory special issue (which has a submission timeline of Nov 1.}

\newpage

Social network research relies heavily on data visualization [@freeman2004]. 
These visualizations can serve to characterize, simplify, and focus theoretical or empirical claims [@moody2005; @rawlings2023]. 
Visualizations are generally more readily digestible than tables of seemingly endless coefficients, significance tests, and summary statistics [@healy2018; @schwabish2021]. 
Additionally, with the increasing ubiquity of network verbiage in society, they can even convey ideas in ways that require less "translation" work for audiences who sit outside of academic and research niches [@sayama2016; @harrington2013]. 
Quite simply, network visualization is not only common, but can be incredibly useful [@birkett2021].^[As with any data presentation strategy--visual or otherwise--there are also ample examples of how to do this poorly (e.g., what have come to be known as unintelligible network "hairballs"); I have a few published visuals of my own that I'd *substantially* rework if given the opportunity today.]

Traditionally, this has taken the form of directly visualizing instances(s) of empirically **observed** social networks--whether snapshots of single data waves, or evolving network "movies" for dynamic relational data patterns [@ognyanova2025].^[These typically occur *after* data pre-processing has taken place (e.g., cleaning, recoding, etc.), but no further data reduction steps (i.e., are not the product of data *summaries* or analytic interpretations).]
That is, such visualizations are intended to characterize the data *per se*. 
While this practice predominates, it's worth asking: 
(1) why we visualize, and 
(2) what optimal set of principles govern strategies for accomplishing those aims, then 
(3) whether an alternative strategy serves those *purposes* and *needs* better than the existing approach?

In this paper, my answers to this set of questions suggests many practices of social network visualization are currently misaligned to their purposes--or more precisely, assumes a single visualization orientation can successfully address multiple (sets of) aims. 
As is often the case with split allegiances, I contend the predominant strategy leads us to occasionally miss the mark, especially when attempting to convey the *theoretical* takeaways of social networks research.

To address this misalignment, I propose that many (though notably, not all) purposes of social network visualizations would be better served by visualizing modeled networks rather than observed network data. 
After making this case following the motivations above, I illustrate this shift in three ways--a trivial example common to how many of us already teach social network modeling, describing a parallel strategy common in non-networks research, and an applied example from a recent research paper.

Before continuing, I should emphasize one thing--when I say "model" I intend this usage in a *theoretical* not a *statistical* sense. 
I avoid relegating this point to a footnote to highlight that the strategy I encourage does not apply only to statistically modeled results. 
Moreover, I should emphasize that this broader applicability in some ways reflects that my proposal in places *imports* practices from non-statistical orientations to network research as much as (or perhaps even more so) than developing a method for statistical applications that can be exported to other use cases.
That caveat noted, my illustrations below will primarily draw on statistical applications as a concrete demonstration; but I will include how the *principles* demonstrated are applicable beyond these particularities.^[Specifically, some of the elements proposed below are directly adopted from other corners of SNA where they are already variably common practices (if labeled differently), and (partially) pave the way for how statistically oriented researchers can implement the approach.]

## Purposes of (network) visualization
So, what are the benefits of network data visualizations? 
And what are the principles we should follow to best accomplish those aims? 
Here, I begin from the assumption that SNA visualizations seek to optimize their *scientific utility*, and highlight some shortcomings that have emerged in our common practices, which have weakened our ability to accomplish those aims--particularly by assuming single visualization strategies can address multiple (sometimes competing) sets of aims.

Many of the benefits for network scholarship mirror those that motivate data visualization in science more broadly [@rawlings2023]. 
A fundamental premise is that data visualization enhances **memory** [@schwabish2021]; this reflects what we know from a number of old adages--including that there's simply value in beauty [@tufte2006, @halpern2015]. 
Moreover, this memory benefit leverages the potential **efficiency** available in data visualization that simply cannot be achieved in other strategies for presenting evidence [@healy2018].
Edward Tufte has prioritized not only using this benefit, but attempting to find ways to optimize it, e.g., via efforts to maximize what he conceptualized as the "ink-to-information" ratio [@tufte1983].
These memory-oriented enhancements can arise both via improved recall and encoding processes--on the latter, the simple act of including visualizations can enhance memory via the complementary of multimodal communication strategies, dovetailing with the strengths and weaknesses of text [@sweller1988].

The data we use to represent social processes are almost always inherently high-dimensional, and visualizations provide a means for *simplifying* that complexity in structured, interpretable formats [@wickham2023a].^[Some contend that this is a *constraint* of data visualization imposed on data presentation strategies (by obfuscating its richness), rather than its benefit [@healy2014].]
This leads visualizations to not only enhance communicative aims, but also to improve readers' ability to understand and interpret complex social phenomenon [@schwabish2021]. 
While statistics can summarize data in principled ways, data visualization rarely simply mimics these other forms and representations of data reduction. 
Instead, they are also "attention-drawing" efforts that highlight certain features of the data, while typically necessitating the deprioritization of others [@leifer1992].

So, how do network scholars *in particular* prioritize these combating aims?
Network scholars especially leverage these dimension reduction approaches by translating summaries of (theoretically) salient social space into the particular strategies for visualization forms [@rawlings2023]. 
For example, one such "attention-drawing" move researchers engage in can seek to highlight certain elements of (theoretically salient) relational patterns (e.g., community structure), while deprioritizing others (e.g., homophily).^[For example, to emphasize the changes in political polarization over time in the US Congress, @moody2013 employ increased coarse-graining to highlight *group* size and positioning over time, and juxtapose that against the decreased *individual* positioning and distancing.]

While such trade-offs may seem universally useful, I argue that how researchers prioritize among these various aims should differ according to different stages the research process when we're leveraging visualization as a tool. 
Moreover, I will contend that collapsing the "preferred strategy" across these non-overlapping sets of aims has been one source of limiting the utility of SNA researchers' visualizations.
That is, my hope is the encourage, more, more-varied, particularization uses of visualizations in ways that will afford each instance greater likelihood of achieving the researchers' purposes for visualizing their network(s).
In particular, optimal visualization strategies differ substantially between exploratory [@wickham2023a], conceptual/theoretical [@brady2020], or explanatory aims [@healy2014]. 

### Differentiated aims according to research stage
Given the potential multiplicity of visualization use cases' aims, it is worth considering how readily our current approaches address the prioritization among aims. 
First, if data fidelity, anomalous cases, and idea generation are of particular interest in exploratory analyses, that would prioritize a set of *data* features as the key elements for visualization to highlight. 
As such, exploratory network visualizations can serve to characterize a study population's composition and structural patterns, in ways that help to articulate things like: features that analyses seek to explain, or identify needed pre-processing steps [@wickham2023a].


Second, for conceptual development in formalizing the aims of a research question, visualization likely needs to optimize on elements of the *analytic strategy* - e.g., differentiating which components are explicitly examined, versus which are (unexamined) assumptions.
Conceptually, network visualizations necessitate a concrete articulation of what analyses will and will not explicitly address, highlighting aspects of a theorized social and relational process to be evaluated [@adams2020d].

Third, if being used as a strategy for presenting analytic *results*, the emphasis typically seeks to highlight *theoretical* implications of interpretation.
In social network research with explanatory (even causal) aims, researchers seek to demonstrate how the observations in empirical cases [@kadushin2012], and appropriate analytic strategies conform to expectations in ways that (fail to) allow appropriate theoretical interpretations [@borgatti2011]. 
In this case, visualizations can prioritize that *conformity* over "data fidelity" or theoretical "ideal types" alone, and likely warrants different optimizations to clearly convey those implications [@bender-demoll2005]. 

The above leads to the implication that while all visualization prioritizations and resulting strategies necessarily employ **simplifications**, the potential non-overlaps among those (prioritized) aims could lead to sub-optimal visualizations in a number of distinct ways.

Perhaps most obviously, when researchers construct a visualization to serve one of these purposes (e.g., exploratory data analysis), it will not optimally serve other aims (e.g., explanatory), because the simpllifications necessary for one purpose mask what needs to be optimized for another.
The previous discussion elaborates why we should reject this assumption; whether we have been making it implicitly or intentionally.

Perhaps more problematically, when researchers *assume* (or worse, *require*) visualizations have "universal" benefits, we are presupposing that the purposes of data visualization are necessarily shared. 
One common version of this approach in SNA visuals has been to produce a "descriptive" plot of the observed data, then to "overlay" some features of the theoretical interpretation of analytic results in hopes that readers can be taught to see the "important" signal among the other noise in the data).
Unfortunately, in this case, we are likely to find ourselves in a situations where the visualizations strategies we employ can end up failing to accomplish *any* of our aims well [@pache2010]. 

My contention is that network visualizations are not infrequently commiting one of these two errors.^[For example, in instances where I've wanted to convey the theoretical takeaways from @adams2013 (that different types of "risk partnerships" provide different contributions to overall graph connectivity, even while their node-level differences/combinations are minimal), nearly impossible to convey from the (largely exploratorily oriented) visualization included in the paper--error 1.]

As such, in the remainder of this paper, I elaborate explore two distinct aims. 
The first path seeks to identify a proposed mapping of differentiated prioritizations to optimized visualization strategies.
The second path seeks to demonstrate how "modeled network visualizations" offer a strategy for conveying the theoretical implications of SNA empirical analyses in ways that are presently under-utilized in the field.

## Additional principles for optimal (network) science visualization

Before jumping into those tasks for optimizing multiple scientific purposes in visualizations, I also need to address two other desirable features of (network) data visualization, that any approaches should incorporate.


2. replicability

3. safety
\textcolor{red}{Some text from the previous iteration to incorporate here -} One limitation that I contend especially needs to be more carefully considered among social network researchers. 
Namely, network visualizations often present unique ethical challenges to presenting research (cite Sage book). 
Especially in “closed population” settings (but not only there - see FB example), the potential for deductive disclosure is broad in any presentation of multiple variables (cite cs on this), and network data are uniquely primed to allow serial-revelations of participants’ identities—i.e., the ability to identify one node in a graph (e.g., myself) often heightens the capacity of identifying others’ identities in turn (e.g., my friends). 
To this end, our frequent practice of plotting empirical networks from data collection efforts may undermine principles of confidentiality and minimal risk in ways that should lead us to consider alternate visualization strategies that can simultaneously leverage these strengths while minimizing these potential risks (cite white paper). 
\textcolor{red}{Do I want to tell my story of hand coding the Add Health network from their 4-cycles paper to incorporate that model in my Glee paper?) 

## A synopsis of the traditional approach ?

1. obtain/clean data
1. plot & label
1. interpret

## Plot Modeled, not Raw, Networks 

\textcolor{red}{From here still likely reads according to the old motivation for this piece - primarily ethical considerations, and may need some substantial revision yet to think broader about what's being solved. Especially should be recast as how/whether it accomplishes the list of aims elaborated above.}

My fundamental proposition is simple - instead of plotting the "raw" empirical networks directly presenting data that has been collected and researchers in-turn analyze, we can produce visualizations of modeled network results that arise from those analyses. 
This is not a ground-breaking suggestion. 
In fact, it's a practice many statistical modelers of social network data already enact in practice.
For example,  "eye-balling" consistency of modeled results with observed networks--in tandem with formal statistical tests for goodness of fit--is even typically taught as a helpful practice in model development and fitting processes [@krivitsky2023]. 
However, while we use these heuristic network visualizations to improve model fit (whether for capturing theoretical limitations, or for enhancing stability of estimates), when presenting networks in publications, authors still often resort to presenting the "real" network - often as a first-pass descriptive task to characterize the nature of the network(s) that the subsequent analyses are intended to explain. 
I've done this multiple times myself.

But if our aims in visualizing networks are to clearly, simply, systematically, and ethically 
convey scientifically useful network visualizations \textcolor{red}{(recheck these parallel the way I end up ordering the set above.)}, there's no reason our visualizations need to be of the raw data. 
Modeled network representations can better serve our purposes across these aims.

Let me draw a parallel here. 
Logistic regression coefficients (just like exponential random graph models) are notoriously hard to make substantive sense of on their own (e.g., significance and magnitude of effects are frequently conflated in results interpretations by writers and readers alike). 
A common solution to this has been for researchers to:
(1) gather, pre-process, then provide a descriptive summary of their data to given an overview sense of what the sample being analyzed actually represents, and how key focal features are distributed in the population; 
(2) conduct statistical analyses to investigate the researchers' theoretical aims, which are summarized with traditional combinations of betas, standard errors, log-likelihoods, etc. to represent the fit of those claims to empirical estimation, then 
(3) transform those modeled results into "predicted probabilities" in ways that help interpret what those modeled results "look like" in their implications [@fox2006]. 
To "tell the story" that arises from the model results we don't return to the raw data, provide the individual-level combination of variables for some subset of the population and rely on those case's patterns to convey the implications of our research [in the rare cases that people do, they are often "synthetic" cases, not real ones, e.g.,  @ayala2019]. 
To do so would not only fail to clearly tell the aggregate story we've learned in the course of our theorization and analysis; it would also violate a number of human subjects protections researchers are obligated to follow. 
So why in the network world would we need to effectively present the "real" pattern of relationships from our data as a means to interpret and convey our findings in visual form?

## Implementation

Instead, I suggest that we can follow a similar logic to develop presentation- and publication-worthy network visualizations from our modeled results in ways that accomplish the aims we have for visualizations--perhaps even more clearly than the directly observed versions--while maintaining protections against potential ethical gaps (e.g., deductive disclosure). 
The process I'm recommending follows the same logic as for regression-type models laid out above:

1. Present descriptives as *summary* statistics of the characteristics of one's network(s) being investigated [@neal2024b].
1. Conduct whatever form of analyses are appropriate to the theoretical aims of the research question(s).
1. Compile appropriate analytic overviews of results (e.g., statistics) into summary form. \textcolor{red}{Here I'm going to want to be especially clear that I'm using "model" as primarily a *theoretical* device/claim, not a particular form of (statistical) analysis. I.e., this doesn't have to be e.g., and ergm result.}
1. Visualize "predicted" network(s) that are specified by the corresponding network analytic (model) results from which the researchers' conclusions are reached.

Worth noting that some corners of the field already effectively do this. 
Block images are a coarse-graining analytic result based strategy for presenting model characteristics (e.g., from a stochastic blockmodel), rather than the raw data from which they derive.
Ego network visuals often use heuristic representations of their actual observations.
Network motifs are an attempt to capture common features across a collection of networks, rather than presenting multiple parallel visualizations and attempting to extract those commonalities across the repeated panels.

## Still to be filled in - Example

\textcolor{red}{Work out the "aims" of visualization a bit more concretely, and elaborate how modeled viz may do this even better than raw data viz can.}

...

\textcolor{red}{Let's illustrate this with an example - I do think I want to use an ergm for this, especially given how frequently we already do this in the first place for that modeling framework as a means for interpretting/improving fit of model estimates.}

# References
