---
title: "A Provocation: Visualizing Modeled Social Networks"
author: "jimi adams, University of South Carolina"
date: "`r format(Sys.Date(), '%Y %B %d')`"
output:
  pdf_document: default
  html_document: default
bibliography: modviz.bib
link-citations: yes
---

**Abstract**: Network scholarship regularly leverages visualizations. 
They are thought to enhance readers' recall, interpretation, and simplification of scholar's intended takeaways. 
However, by representing the specifics of single empirical cases, these visualization strategies may not optimize how well they accomplish our scientific purposes. 
In particular, they may: 
(1) be overly complex in ways that obfuscate what we can learn from them, (2) draw attention to the particularities of the case, rather than the general principles the case is examined to characterize, 
(3) be difficult to precisely replicate, raising questions about consistency in interpretation, and 
(4) introduce potential risks that could violate research ethical standards. 
To address these, this paper provokes the field to consider whether presenting *modeled* network results--in lieu of empirical cases--retains the aims of network visualization, while potentially overcoming some of the limitations of existing practice.

NOTE: **Version drafted for submission as an extended abstract for consideration in the special issue of *Social Networks* on social network theory.**

\newpage

Social network research relies heavily on data visualization [@freeman_development_2004]. 
These visualizations can serve to characterize, simplify, and focus theoretical or empirical claims [@moody_dynamic_2005; @rawlings_how_2023]. 
Visualizations generally are often more readily digestible than tables of seemingly endless coefficients, significance tests, and summary statistics [@healy_data_2019; @schwabish_better_2021]. 
Additionally, with the increasing ubiquity of network verbiage in society, they can even convey ideas in ways that require less "translation" work for audiences who sit outside of academic research niches [@sayama_what_2016; @harrington_commentary_2013]. 
Quite simply, network visualization is not only common, but can be incredibly useful [@NetCanvas].^[As with any data presentation strategy--visual or otherwise--there are also ample examples of how to do this poorly (e.g., what have come to be known as unintelligible network "hairballs"); I have a few published visuals of my own I'd *substantially* rework if given the opportunity today.]

Traditionally, this has taken the form of directly visualizing instances(s) of empirical social networks--whether snapshots of single data waves, or evolving network "movies" for dynamic data structures [@katyao_2025].^[These typically occur *after* data pre-processing has taken place (e.g., cleaning, recoding, etc.), but no further data reduction steps (i.e., are not the product of data *summaries* or analytic interpretations)--i.e., they are intended to characterize the data *per se*.] 
While this practice predominates, it's worth asking: 
(1) why we visualize, and 
(2) what optimal set of principles govern strategies for accomplishing those aims, then 
(3) whether an alternative strategy serves those *purposes* and *needs* better than the existing approach?

## Purposes of (network) vizualization
So, what are the benefits of network data visualizations? 
Many of the benefits for network scholarship mirror those that motivate data visualization in science more broadly. 
A fundamental premise is that data visualization enhances **memory** [@schwabish_better_2021]; this reflects what we know from a number of old adages--there's simply value in beauty [@tufte2006beautiful, @halpern2015beautiful]. 
Moreover, this memory benefit leverages the potential **efficiency** available in data visualization that simply cannot be achieved in other strategies for presenting evidence [@healy_data_2019]. 
Edward Tufte has prioritized not only using this benefit, but attempting to optimize with efforts to maximize what he conceptualized as the "ink-to-information" ratio [@tufte1983visual].

In addition to these communicative aims, visualization also demonstrates capacity to enhance our interpretation of complex phenomenon [@schwabish_better_2021]. 
Data for almost all social processes are inherently high-dimensional, and visualizations provide a means for *simplifying* that complexity in reduced formats (@wickham_r_2023).^[Some may contend that this is a *constraint* of data visualization imposed on data presentation strategies rather than its benefit.]
Network visualizations in particular focus on dimension reduction for ease of interpretation [@rawlings_how_2023. 
While statistics can summarize data in principled ways, data visualization efforts rarely simply mimic those data reduction aims, but also involve some claims about attention--drawing our attention to certain features of the data, and deprioritizing others [@leifer_denying_1992]. 
It is worth noting however, that the emphases among the aims above likely differ substantially between visualizations with exploratory [@wickham_r_2023], conceptual/theoretical [@conceptmap], or explanatory aims [@HealyMoody].

## Principles for optimal (network) science visualization

1. Scientifically, visualization's capacity for simplification typically prioritizes the *theoretical* claims being made in data analysis.
For social networks this typically entails explaining elements of relational social processes, via combining **theoretical models** [@borgatti_theory_2011] with some form of empirical data analysis [@kadushin_understanding_2012]-- which visualizations then provide a means to convey [@bender-demoll_art_2005]. 
Models are a *theoretical* tool for simplifying reality in a way that makes them useful reductions of the claims being made about social processes [@adams_TSP2020].
Optimizing *useful* simplifications that offer clarity of the theoretical claims being offered is therefore a fundamental principle governing (network) scientific data visualization.

2. If the aims of visualization are scientific, and not merely heuristic, an additionally desirable quality would allow for ready replication. 
Providing data and code allowing for analyses [@transparent2019] should also facilitate the reproduction of any corresponding visualizations used to represent and communicate those analyses [@bender-demoll_art_2005].

3. Network visualizations often present unique ethical challenges to presenting research [@adams2019sage]. 
Especially in “closed population” settings (but not exclusively @zimmer_but_2010), the potential for deductive disclosure is broad in any presentation of multiple variables, and network data are uniquely primed to allow serial-revelations of participants’ identities—i.e., the ability to identify one node in a graph (e.g., myself) often heightens the capacity of identifying others’ identities in turn (e.g., my friends). 
To this end, our frequent practice of directly plotting observed networks may undermine principles of confidentiality and minimal risk in ways that should lead us to consider alternate visualization strategies that can simultaneously leverage these strengths while minimizing these potential risks [@INSNA26-ethics]. 


## A synopsis of the traditional approach

1. obtain/clean data
1. plot & label
1. interpret

## Plot Modeled, not Observed, Networks 

My fundamental proposition is simple - instead of plotting the "observed" empirical networks directly presenting data that has been collected and researchers in-turn analyze, we can produce visualizations of modeled network results that arise from those analyses. 
This is not a ground-breaking suggestion. 
In fact, it's a practice many statistical modelers of social network data already enact in practice.
For example,  "eye-balling" consistency of modeled results with observed networks--in tandem with formal statistical tests for goodness of fit--is even typically taught as a helpful practice in model development and fitting processes [@krivitsky_ergm_2023]. 
However, while we use these heuristic network visualizations to improve model fit (whether for capturing theoretical limitations, or for enhancing stability of estimates), when presenting networks in publications, authors still often resort to presenting the "real" network - often as a first-pass descriptive task to characterize the nature of the network(s) that the subsequent analyses are intended to explain. 
I've done this multiple times myself.

But if our aims in visualizing networks are to clearly, simply, systematically, and ethically 
convey scientifically useful network visualizations, there's no reason our visualizations *need* to be of the observed data. 
Modeled network representations can potentially better serve our purposes across these aims.

Let me draw a parallel here. 
Logistic regression coefficients (just like exponential random graph models) are notoriously hard to make substantive sense of on their own (e.g., significance and magnitude of effects are frequently conflated in results interpretations by writers and readers alike). 
A common solution to this has been for researchers to:
(1) gather, pre-process, then provide a descriptive summary of their data to given an overview sense of what the sample being analyzed actually represents, and how key focal features are distributed in the population; 
(2) conduct statistical analyses to investigate the researchers' theoretical aims, which are summarized with traditional combinations of betas, standard errors, log-likelihoods, etc. to represent the fit of those claims to empirical estimation, then 
(3) transform those modeled results into "predicted probabilities" in ways that help interpret what those modeled results "look like" in their implications [@fox_effect_2006]. 
To "tell the story" that arises from the model results we don't return to the observed data, provide the individual-level combination of variables for some subset of the population and rely on those case's patterns to convey the implications of our research [in the rare cases that people do, they are often "synthetic" cases, not real ones, e.g.,  @ayala_image_2019]. 
To do so would not only fail to clearly tell the aggregate story we've learned in the course of our theorization and analysis; it would also violate a number of human subjects protections researchers are obligated to follow. 
So why in the network world would we need to effectively present the "real" pattern of relationships from our data as a means to interpret and convey our findings in visual form?

## Implementation

Instead, I suggest that we can follow a similar logic to develop presentation- and publication-worthy network visualizations from our modeled results in ways that accomplish the aims we have for visualizations--perhaps even more clearly than the directly observed versions--while maintaining protections against potential ethical gaps (e.g., deductive disclosure). 
The process I'm recommending follows the same logic as for regression-type models laid out above:

1. Present descriptives as *summary* statistics of the characteristics of one's network(s) being investigated [@Neal_2024].
1. Conduct whatever form of analyses are appropriate to the theoretical aims of the research question(s).
1. Compile appropriate analytic overviews of modeled results (e.g., statistics) into summary form.^(It is important to emphasize here that I am using "model" in a *theoretical* nature here, not necessarily a statistical one.)
1. Visualize "predicted" network(s) that are specified by the corresponding network analytic (model) results from which the researchers' conclusions are reached.

It is crucially worth noting that  some corners of the field already effectively do this. 
Block images are a coarse-graining analytical result based strategy for presenting model characteristics (e.g., from a stochastic blockmodel), rather than the observed data from which they derive.
Ego network visuals often use heuristic representations of their actual observations.
Network motifs are an attempt to capture common features across a collection of networks, rather than presenting multiple parallel visualizations of individuals actual networks, then attempting to extract those commonalities across the repeated panels.

## Still to be filled in - Example
I will illustrate the utility of the approach with an example from an exponential random graph model's results. The takeaway will emphasize that we can accomplish the aims of social network visualization as well--and in some ways *better*--with this approach than we can when directly visualizing observed data.

# References